In [1]:
%load_ext autoreload
%autoreload 2
import sys 
from FR3Py.robot.interface import FR3Real
robot = FR3Real(robot_id='fr3')

Interface Running...


In [2]:
robot.getJointStates()

{'q': array([ 9.69113370e-04, -7.84731326e-01, -2.55507584e-06, -2.38915525e+00,
         9.01109104e-05,  1.57101440e+00,  7.86523983e-01]),
 'dq': array([ 1.51213469e-03, -1.18833623e-03,  8.34295386e-04,  9.25195677e-04,
         2.49131064e-05, -8.76247010e-05,  1.11746836e-03]),
 'T': array([-0.18716741, -4.14727926, -0.64864194, 23.07193375,  0.90013349,
         2.06174445, -0.11578915])}

In [43]:
import numpy as np
import time

static_friction = np.array([0.8, 1.1, 0.5, 1.7, 1.8, 1.0, 0.6])
signs = np.array([1,-1,-1,1,1,-1,-1])

[ 0.8 -1.1 -0.5  1.7  1.8 -1.  -0.6]


In [42]:

tau = np.array([0., 0., 0., 0., 0., 0., 0.])
info = robot.getJointStates()
dq_prev = info['dq']
q_prev = info['q']
joint_id = 6

for i in range(30):
    info = robot.getJointStates()
    q = info['q']
    dq = info['dq']
    if np.abs(q[joint_id] - q_prev[joint_id]) > 1e-2:
        break
    
    tau[joint_id] += 0.1
    robot.setCommands(tau)
    time.sleep(1)
    print(tau)
robot.setCommands(np.zeros(7))
print(tau)

[0.  0.  0.  0.  0.  0.  0.1]
[0.  0.  0.  0.  0.  0.  0.2]
[0.  0.  0.  0.  0.  0.  0.3]
[0.  0.  0.  0.  0.  0.  0.4]
[0.  0.  0.  0.  0.  0.  0.5]
[0.  0.  0.  0.  0.  0.  0.6]
[0.  0.  0.  0.  0.  0.  0.6]
