In [1]:
%load_ext autoreload
%autoreload 2
import sys 
from FR3Py.robot.interface import FR3Real
robot = FR3Real(robot_id='fr3')

Interface Running...


In [2]:
robot.getJointStates()

{'q': array([ 7.97622967e-04, -7.84783699e-01,  1.40470825e-04, -2.35834433e+00,
         5.17115632e-04,  1.57123112e+00,  7.86902855e-01]),
 'dq': array([-4.83298170e-04, -3.05536135e-04,  1.30129210e-03,  6.59455255e-04,
        -8.18993450e-04,  2.68265687e-04,  5.19932380e-05]),
 'T': array([-0.15939641, -4.32183981, -0.72402036, 23.19888687,  0.65385664,
         2.12125373, -0.07642147]),
 'M': array([[ 4.93341874e-01, -8.95682441e-03,  4.90972166e-01,
         -1.19238455e-02,  6.15481633e-02, -3.06599302e-03,
          1.29639081e-03],
        [-8.95682441e-03,  1.54588109e+00,  4.74714223e-03,
         -7.00805061e-01, -1.29214957e-02, -2.24156724e-02,
         -1.53844326e-03],
        [ 4.90972166e-01,  4.74714223e-03,  9.93514327e-01,
         -2.58602116e-02,  7.49685918e-02, -3.84236815e-03,
          3.24953975e-03],
        [-1.19238455e-02, -7.00805061e-01, -2.58602116e-02,
          9.73363824e-01,  2.55880571e-02,  1.11775517e-01,
         -1.72131526e-04],
        

In [4]:
import numpy as np
import time

static_friction = np.array([0.8, 1.1, 0.5, 1.2, 1.3, 1.0, 0.5])

In [11]:

tau = np.array([0., 0., 0., 0., 0., 0., 0.])
info = robot.getJointStates()
dq_prev = info['dq']
q_prev = info['q']
joint_id = 6

for i in range(30):
    info = robot.getJointStates()
    q = info['q']
    dq = info['dq']
    if np.abs(q[joint_id] - q_prev[joint_id]) > 1e-2:
        break
    
    tau[joint_id] += 0.1
    robot.setCommands(tau)
    time.sleep(1)
    print(tau)
robot.setCommands(np.zeros(7))
print(tau)

[0.  0.  0.  0.  0.  0.  0.1]
[0.  0.  0.  0.  0.  0.  0.2]
[0.  0.  0.  0.  0.  0.  0.3]
[0.  0.  0.  0.  0.  0.  0.4]
[0.  0.  0.  0.  0.  0.  0.5]
[0.  0.  0.  0.  0.  0.  0.5]
